/* Acervo da Totali Garage — dados de demonstração.
   Substitua por fotos reais em /totali-garage/assets/carros/ quando disponíveis;
   por ora cada carro usa uma "vitrine" gerada em SVG (ver photo-art.js). */

const CARS = [
  {
    id: "toyota-sw4-diamond-2026",
    marca: "Toyota",
    modelo: "SW4",
    versao: "Diamond 7 Lugares",
    ano: 2026,
    categoria: "SUV",
    cor: "Branco",
    corHex: "#eef0ee",
    km: 12000,
    cambio: "Automático",
    combustivel: "Diesel",
    portas: 5,
    preco: 389990,
    fipe: 419990,
    destaque: true,
    fotos: [
      "assets/carros/toyota-sw4-diamond-2026/1-frontal.jpg",
      "assets/carros/toyota-sw4-diamond-2026/2-traseira.jpg",
    ],
    fotoLabels: ["Frontal", "Traseira"],
    descricao:
      "O SUV mais completo da linha Toyota, na versão topo de linha Diamond com 7 lugares. Praticamente zero km, com acabamento premium e bancos em couro em toda a cabine.",
    diferenciais: ["7 lugares", "Bancos em couro", "Acabamento premium"],
  },
  {
    id: "porsche-911-carrera-2021",
    marca: "Porsche",
    modelo: "911 Carrera",
    versao: "S Coupé",
    ano: 2021,
    categoria: "Esportivo",
    cor: "Preto Ébano",
    corHex: "#161616",
    km: 18500,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 2,
    preco: 890000,
    fipe: 945000,
    destaque: true,
    descricao:
      "Um dos ícones mais desejados do mundo automotivo, com motor 3.0 flat-six biturbo e dinâmica de pilotagem incomparável. Unidade de garagem, revisada na concessionária e com histórico 100% documentado.",
    diferenciais: ["Único dono", "Revisões em dia", "Bancos em couro Alcântara", "Escapamento esportivo"],
  },
  {
    id: "porsche-macan-2022",
    marca: "Porsche",
    modelo: "Macan",
    versao: "S",
    ano: 2022,
    categoria: "SUV",
    cor: "Branco Carrara",
    corHex: "#f2f2f0",
    km: 24000,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 520000,
    fipe: 561000,
    destaque: false,
    descricao:
      "SUV esportivo com acabamento premium, tração integral e o equilíbrio perfeito entre conforto para o dia a dia e prazer de dirigir.",
    diferenciais: ["Teto solar panorâmico", "Central multimídia atualizada", "Rodas aro 21", "IPVA quitado"],
  },
  {
    id: "bmw-m4-competition-2023",
    marca: "BMW",
    modelo: "M4",
    versao: "Competition",
    ano: 2023,
    categoria: "Esportivo",
    cor: "Azul Isle of Man",
    corHex: "#1c3d6b",
    km: 9800,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 2,
    preco: 780000,
    fipe: 832000,
    destaque: true,
    descricao:
      "Coupé esportivo de altíssima performance, 510 cv e presença de campeonato. Praticamente zero km, com garantia de fábrica vigente.",
    diferenciais: ["Garantia de fábrica", "Freios M Carbon Ceramic", "Pintura especial", "Estado de zero km"],
  },
  {
    id: "range-rover-velar-2021",
    marca: "Land Rover",
    modelo: "Range Rover Velar",
    versao: "R-Dynamic HSE",
    ano: 2021,
    categoria: "SUV",
    cor: "Cinza Byron",
    corHex: "#4a4d52",
    km: 31200,
    cambio: "Automático",
    combustivel: "Diesel",
    portas: 4,
    preco: 465000,
    fipe: 512000,
    destaque: false,
    descricao:
      "Design escultural e sofisticação britânica. Interior revestido em couro Windsor, perfeito equilíbrio entre elegância urbana e capacidade off-road.",
    diferenciais: ["Bancos ventilados", "Suspensão a ar", "Câmera 360°", "Revisado na Land Rover"],
  },
  {
    id: "mercedes-c300-amg-2022",
    marca: "Mercedes-Benz",
    modelo: "C 300",
    versao: "AMG Line",
    ano: 2022,
    categoria: "Sedã",
    cor: "Prata Diamante",
    corHex: "#c7c9cc",
    km: 15400,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 385000,
    fipe: 419000,
    destaque: false,
    descricao:
      "Elegância e tecnologia embarcada de ponta, com pacote esportivo AMG. Um sedã que impõe presença sem abrir mão do conforto executivo.",
    diferenciais: ["Painel MBUX duplo", "Bancos multicontorno", "Piloto automático adaptativo", "Único dono"],
  },
  {
    id: "audi-rs5-2020",
    marca: "Audi",
    modelo: "RS5",
    versao: "Sportback",
    ano: 2020,
    categoria: "Esportivo",
    cor: "Cinza Nardo",
    corHex: "#8d8f8c",
    km: 27600,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 545000,
    fipe: 598000,
    destaque: false,
    descricao:
      "A raridade de um esportivo de quatro portas: tração quattro, motor V6 biturbo e acabamento Audi Exclusive.",
    diferenciais: ["Tração quattro", "Bancos RS em couro", "Escapamento esportivo", "Revisões na concessionária"],
  },
  {
    id: "jeep-grand-cherokee-srt-2021",
    marca: "Jeep",
    modelo: "Grand Cherokee",
    versao: "SRT",
    ano: 2021,
    categoria: "SUV",
    cor: "Preto Diamante",
    corHex: "#1a1a1a",
    km: 22300,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 415000,
    fipe: 458000,
    destaque: true,
    descricao:
      "Potência de 468 cv em um SUV pensado para quem exige performance sem abrir mão do espaço e do conforto para a família.",
    diferenciais: ["Motor V8 6.4", "Freios Brembo", "Teto solar", "Pacote de som premium"],
  },
  {
    id: "volvo-xc90-2022",
    marca: "Volvo",
    modelo: "XC90",
    versao: "T6 Inscription",
    ano: 2022,
    categoria: "SUV",
    cor: "Azul Denim",
    corHex: "#2b3d55",
    km: 19200,
    cambio: "Automático",
    combustivel: "Híbrido",
    portas: 4,
    preco: 468000,
    fipe: 505000,
    destaque: false,
    descricao:
      "SUV de sete lugares com o equilíbrio escandinavo entre segurança, sofisticação e tecnologia híbrida.",
    diferenciais: ["7 lugares", "Motorização híbrida", "Bancos em couro Nappa", "Head-up display"],
  },
  {
    id: "lexus-es300h-2021",
    marca: "Lexus",
    modelo: "ES 300h",
    versao: "Premium",
    ano: 2021,
    categoria: "Sedã",
    cor: "Branco Pérola",
    corHex: "#eeeeee",
    km: 26800,
    cambio: "Automático (CVT)",
    combustivel: "Híbrido",
    portas: 4,
    preco: 329000,
    fipe: 361000,
    destaque: false,
    descricao:
      "Conforto silencioso e economia híbrida em um sedã que traduz a filosofia japonesa de luxo discreto e confiável.",
    diferenciais: ["Motorização híbrida", "Bancos com massagem", "Mark Levinson Audio", "Manual e chave reserva"],
  },
  {
    id: "toyota-hilux-srx-2023",
    marca: "Toyota",
    modelo: "Hilux",
    versao: "SRX Diamond 4x4",
    ano: 2023,
    categoria: "Picape",
    cor: "Prata Metálico",
    corHex: "#b8bcc0",
    km: 12100,
    cambio: "Automático",
    combustivel: "Diesel",
    portas: 4,
    preco: 335000,
    fipe: 358000,
    destaque: false,
    descricao:
      "A picape mais desejada do país na sua versão topo de linha, com robustez comprovada e acabamento de SUV premium.",
    diferenciais: ["Tração 4x4", "Central multimídia 9\"", "Bancos em couro", "Revisões na Toyota"],
  },
  {
    id: "bmw-x6-m50i-2022",
    marca: "BMW",
    modelo: "X6",
    versao: "M50i",
    ano: 2022,
    categoria: "SUV",
    cor: "Cinza Sophisto",
    corHex: "#6b6d70",
    km: 16700,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 725000,
    fipe: 779000,
    destaque: true,
    descricao:
      "Design coupé de SUV com performance de esportivo: motor V8 biturbo de 530 cv em uma carroceria imponente.",
    diferenciais: ["Motor V8 Biturbo", "Rodas aro 22", "Bancos com massagem", "Faróis Laser"],
  },
  {
    id: "jaguar-f-pace-2021",
    marca: "Jaguar",
    modelo: "F-Pace",
    versao: "R-Sport",
    ano: 2021,
    categoria: "SUV",
    cor: "Verde British",
    corHex: "#28352b",
    km: 29500,
    cambio: "Automático",
    combustivel: "Diesel",
    portas: 4,
    preco: 398000,
    fipe: 437000,
    destaque: false,
    descricao:
      "A alma esportiva da Jaguar em formato SUV, com linhas elegantes e uma condução precisa que remete aos esportivos da marca.",
    diferenciais: ["Tração integral", "Painel digital", "Bancos aquecidos e ventilados", "Único dono"],
  },
  {
    id: "porsche-panamera-2020",
    marca: "Porsche",
    modelo: "Panamera",
    versao: "4S",
    ano: 2020,
    categoria: "Sedã",
    cor: "Vermelho Carmim",
    corHex: "#7a1f1f",
    km: 33400,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 685000,
    fipe: 742000,
    destaque: false,
    descricao:
      "Um sedã com alma de esportivo: motor V6 biturbo, tração integral e o refinamento que só a Porsche entrega.",
    diferenciais: ["Suspensão pneumática", "Bancos em couro integral", "Teto solar panorâmico", "Revisões em dia"],
  },
  {
    id: "audi-q8-2022",
    marca: "Audi",
    modelo: "Q8",
    versao: "Performance",
    ano: 2022,
    categoria: "SUV",
    cor: "Cinza Daytona",
    corHex: "#5a5c5f",
    km: 20100,
    cambio: "Automático",
    combustivel: "Gasolina",
    portas: 4,
    preco: 615000,
    fipe: 662000,
    destaque: false,
    descricao:
      "O topo da linha de SUVs da Audi: presença imponente, cabine tecnológica com três telas e tração quattro de série.",
    diferenciais: ["Tração quattro", "Três telas digitais", "Bancos ventilados", "Rodas aro 22"],
  },
];

const CATEGORIAS = ["Todos", ...Array.from(new Set(CARS.map((c) => c.categoria)))];
